### ISSUE TITLE
Time to update to match the new UIs? And maybe add some example screenshots?

### ISSUE THREAD

**Issue by PieButNotThatPie** [belmarca/opnsense-wireguard-android#1]

**Comment by belmarca** [comment]
Hi,

I would have to work through the process again. Are the instructions currently unusable?

**Comment by PieButNotThatPie** [comment]
It's still very much usable, mostly changes in titles and section names etc actually

**Comment by belmarca** [comment]
Hi @PieButNotThatPie,

I am not using opnsense anymore. I have migrated to vanilla OpenBSD. If you or someone else want to change the screenshots just send a PR. I will leave this repo as is but feel free to send a PR or fork to update :)
